// Generated by CoffeeScript 1.10.0

/*
 * Testing Program
 *
 * 1. Successfully get and return the YAML document
 * 2. Return suggestions that match a search term
 *
 */
var By, assert, chai, expect, port, selenium;

assert = require('assert');

chai = require('chai');

chai.use(require('chai-as-promised'));

selenium = require('selenium-webdriver');

By = selenium.By;

expect = chai.expect;

port = 3300;

before(function() {
  return this.driver = new selenium.Builder().withCapabilities(selenium.Capabilities.chrome()).build();
});

after(function() {});

describe('WebDriver Autocomplete Test', function() {
  this.timeout(100000);
  beforeEach(function() {
    return this.driver.get('http://localhost:8000');
  });
  it('checks if the widget has loaded', function() {
    var inputBox;
    inputBox = this.driver.findElement({
      id: 'yaml_member_search_box'
    });
    return assert(inputBox);
  });
  it('displays correct suggestions', function() {
    this.driver.findElement({
      id: 'yaml_member_search_box'
    }).then(function(inputBox) {
      inputBox.click();
      inputBox.sendKeys('TD Canada');
      return inputBox.sendKeys(selenium.Key.ENTER);
    });
    this.driver.sleep(1000);
    return this.driver.findElement({
      css: '.autocomplete-suggestion'
    }).then(function(suggestion) {
      var dataval;
      return dataval = suggestion.getText();
    });
  });
  it('closes the result window', function() {
    return this.driver.findElement({
      id: 'yaml_member_search_box'
    }).then(function(inputBox) {
      inputBox.click();
      inputBox.sendKeys('TD Canada');
      return inputBox.sendKeys(selenium.Key.ENTER);
    });
  });
  return it('searches for multiple items', function() {
    this.driver.findElement({
      id: 'yaml_member_search_box'
    }).then(function(inputBox) {
      inputBox.click();
      inputBox.sendKeys('TD Canada');
      return inputBox.sendKeys(selenium.Key.ENTER);
    });
    this.driver.sleep(1000);
    this.driver.findElement({
      id: 'yaml_member_result_close'
    }).click();
    this.driver.sleep(500);
    this.driver.findElement({
      id: 'yaml_member_search_box'
    }).then(function(inputBox) {
      inputBox.click();
      inputBox.sendKeys('Royal Bank');
      return inputBox.sendKeys(selenium.Key.ENTER);
    });
    this.driver.sleep(500);
    this.driver.findElement({
      id: 'yaml_member_result_close'
    }).click();
    this.driver.sleep(250);
    this.driver.findElement({
      id: 'yaml_member_search_box'
    }).then(function(inputBox) {
      inputBox.click();
      inputBox.sendKeys('TD Bank');
      return inputBox.sendKeys(selenium.Key.ENTER);
    });
    this.driver.sleep(500);
    return this.driver.findElement({
      id: 'yaml_member_result_close'
    }).click();
  });
});
